import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

export default function CommissionRules({ auth, rules = [] }) {
  const [editing, setEditing] = useState(null)
  const { data, setData, post, processing, errors, reset } = useForm({ nombre: '', minimo: '', maximo: '', monto_mxn: '', vigente_desde: '' });
  const submit = e => { e.preventDefault(); post(route('commission-rules.store'), { onSuccess: () => { if (editing) router.delete(route('commission-rules.destroy', editing.id)); reset(); setEditing(null) } }); };
  const edit = rule => { setEditing(rule); setData({ nombre: rule.nombre, minimo: rule.minimo, maximo: rule.maximo ?? '', monto_mxn: rule.monto_mxn, vigente_desde: '' }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const deactivate = id => { if (confirm('¿Desactivar esta regla? No afectará comisiones ya aplicadas.')) router.delete(route('commission-rules.destroy', id)); };
  return <AuthenticatedLayout user={auth.user} header={<h2 className="text-xl font-semibold">Reglas de comisión</h2>}><Head title="Reglas de comisión" />
    <div className="bg-slate-100 py-10"><div className="mx-auto max-w-6xl space-y-6 px-4">
      <section className="rounded-xl bg-slate-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.25em] text-cyan-300">Configuración comercial</p><h1 className="mt-2 text-3xl font-black">Reglas de recuperación</h1><p className="mt-2 text-slate-300">Los cambios aplican únicamente a pagos futuros; el histórico queda protegido.</p></section>
      <section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">{editing ? `Editar ${editing.nombre}` : 'Programar nueva regla'}</h2>{editing && <button onClick={()=>{reset();setEditing(null)}} className="text-sm text-slate-500">Cancelar edición</button>}</div><p className="mt-1 text-sm text-slate-500">{editing ? 'Se creará una nueva versión; la anterior se conservará en el historial.' : 'Define el escalón y su importe por recuperación.'}</p><form className="mt-4 grid gap-3 md:grid-cols-5" onSubmit={submit}><input required placeholder="Nombre" value={data.nombre} onChange={e=>setData('nombre',e.target.value)} className="rounded border p-2"/><input required type="number" min="1" placeholder="Desde" value={data.minimo} onChange={e=>setData('minimo',e.target.value)} className="rounded border p-2"/><input type="number" min="1" placeholder="Hasta (vacío = +)" value={data.maximo} onChange={e=>setData('maximo',e.target.value)} className="rounded border p-2"/><input required type="number" min="0" placeholder="MXN por recuperación" value={data.monto_mxn} onChange={e=>setData('monto_mxn',e.target.value)} className="rounded border p-2"/><button disabled={processing} className="rounded bg-sky-700 p-2 font-bold text-white">{editing ? 'Crear nueva versión' : 'Guardar regla'}</button></form>{Object.values(errors).map(x=><p className="mt-2 text-sm text-red-600" key={x}>{x}</p>)}</section>
      <section className="grid gap-4 md:grid-cols-3">{rules.filter(r=>r.activa).map(rule=><article key={rule.id} className="rounded-xl border border-sky-100 bg-white p-5 shadow-sm"><div className="flex justify-between"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Activa</span><small className="text-slate-400">v{rule.version}</small></div><h3 className="mt-4 font-black text-slate-900">{rule.minimo}–{rule.maximo ?? '+'} recuperaciones</h3><p className="mt-2 text-3xl font-black text-sky-800">${Number(rule.monto_mxn).toFixed(0)} <small className="text-sm">MXN</small></p><p className="mt-2 text-xs text-slate-500">Vigente desde {new Date(rule.vigente_desde).toLocaleDateString('es-MX')}</p><div className="mt-4 flex gap-3"><button onClick={()=>edit(rule)} className="font-bold text-sky-700">Editar</button><button onClick={()=>deactivate(rule.id)} className="font-bold text-red-600">Desactivar</button></div></article>)}</section>
    </div></div></AuthenticatedLayout>;
}
