<?php

return [
    'individual_therapy' => 'Terapia individual',
    'couples_therapy' => 'Terapia de pareja',
    'family_therapy' => 'Terapia familiar',
    'group_therapy' => 'Terapia grupal',
    'psychological_assessment' => 'Evaluación psicológica',
    'cognitive_behavioral_therapy' => 'Terapia cognitivo-conductual (TCC)',
    'psychoanalytic_therapy' => 'Terapia psicoanalítica',
    'humanistic_therapy' => 'Terapia humanista',
    'acceptance_commitment_therapy' => 'Terapia de aceptación y compromiso (ACT)',
    'dialectical_behavior_therapy' => 'Terapia dialéctica conductual (DBT)',
    'exposure_therapy' => 'Terapia de exposición',
    'play_therapy' => 'Terapia de juego',
    'art_therapy' => 'Terapia de arte',
    'relaxation_therapy' => 'Terapia de relajación',
    'hypnotherapy' => 'Hipnoterapia',
    'sex_therapy' => 'Terapia sexual',
    'grief_therapy' => 'Terapia de duelo',
    'addiction_therapy' => 'Terapia de adicciones',
    'trauma_therapy' => 'Terapia de trauma',
    'supportive_therapy' => 'Terapia de apoyo',
    'mindfulness_therapy' => 'Terapia basada en mindfulness',
    'neurofeedback_therapy' => 'Terapia de neurofeedback',
    'cognitive_rehabilitation_therapy' => 'Rehabilitación cognitiva',
    'crisis_intervention_therapy' => 'Intervención en crisis',
    'personal_development_therapy' => 'Terapia de desarrollo personal',
    'stress_management_therapy' => 'Manejo del estrés',
    'self_esteem_therapy' => 'Terapia de autoestima',
    'emotional_regulation_therapy' => 'Terapia de regulación emocional',
    'sensory_integration_therapy' => 'Terapia de integración sensorial',
    'cognitive_restructuring_therapy' => 'Reestructuración cognitiva',
    'positive_psychology_therapy' => 'Psicología positiva',
    'palliative_therapy' => 'Acompañamiento psicológico paliativo',
];
